# Generated by Django 4.0.8 on 2023-01-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_site_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='understood',
        ),
    ]
