# Generated by Django 4.0.8 on 2023-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='is_understood',
            field=models.BooleanField(default=False),
        ),
    ]
