# Generated by Django 4.0.8 on 2023-02-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.site'),
        ),
    ]
