# Generated by Django 4.0.8 on 2023-02-17 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='date_first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
