# Generated by Django 4.0.8 on 2023-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_userprogress_date_first_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='date_last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
