# Generated by Django 4.0.8 on 2023-02-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_userprogress_date_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='date_understood',
            field=models.DateTimeField(null=True),
        ),
    ]
