# Generated by Django 4.0.8 on 2023-02-17 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_userprogress_date_understood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='date_understood',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
