# Generated by Django 4.0.8 on 2023-02-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_userprogress_date_understood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='date_understood',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
