# Generated by Django 4.0.8 on 2023-02-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_alter_userprogress_date_understood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='times_seen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
